### PR TITLE
upload converted notebook

### PR DESCRIPTION
**Pull request by ambrosejcarr**
* adds converted MERFISH notebook. 
* verified works by converting back and running notebook

### CODE REVIEW

**Comment by dganguli** [comment]
sweet

**Comment by ttung** [comment]
This should be the same file name as the original `.ipynb`, except with a different extension.  #81 will be expecting that.

**Comment by ambrosejcarr** [comment]
Fixed naming.

**Comment by ambrosejcarr** [comment]
Duplicate of #82

**Pull request closed without merging**
